name: Execute lint, format and tests on pull request

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-format-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run formatter
        run: npm run format -- --check

      - name: Run tests
        run: npm test
